postcontents/urls.py
from django.urls import path

from . import views
app_name = 'postcontents'

urlpatterns =[
    path('<int:id>/', views.postpage, name='postpage'),
    path('content/<int:id>/', views.contents, name='contents'),
    path('otherprofile/<str:parameter>/', views.otherprofile, name='otherprofile')
] 

tk2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('postcontents/', include('postcontents.urls')),
    path('form/', include('form.urls', namespace='form')),
    path('', include('main.urls')),
    path('',include('users.urls')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from . import views as user_views
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('profile-update/', user_views.profile_update, name='profile_update'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('search-username/',user_views.getDataAllUser, name="search_username"),
    # path('register-check/',user_views.registerCheck, name="register_check"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg',upload_to='profile_pics')

    def __str__(self):
        return self.user.username

    def save(self, force_insert=False, force_update=False, using=None):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 400 or img.height > 400 :
            output_size = (400,400)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email','password1','password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

users/views.py
from django.shortcuts import render, redirect, reverse
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.models import User
from .models import Profile, User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from form.models import PostModel
from django.http import HttpResponse, JsonResponse
from django.core.serializers import serialize
import json

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            new_user = authenticate(
                username = username,
                password = form.cleaned_data['password1']
            )
            new_profile = Profile.objects.create(user=new_user)
            # messages.success(request, f'Account {username} has been created. Please Log In!')
            
            return HttpResponse('success')
    else :
        form = UserRegisterForm()
        return render(request,'user/register.html',{'form': form, 'usercount': User.objects.all().count() })

# def registerCheck(request):
#     form = UserRegisterForm(request.POST)
#     if (form.is_valid()!=True):
#         return HttpResponse('failed')
#     else : 
#         return HttpResponse('success')


def getDataAllUser(request):
    data_raw = serialize('json', User.objects.all())
    data = json.loads(data_raw)
    return JsonResponse(data,safe=False)

@login_required
def profile(request):
    context = {
        'posts' : PostModel.objects.filter(author=request.user),
        'author':request.user
    }
    return render(request, 'user/profile.html',context)

@login_required
def profile_update(request):
    if request.method == 'POST':
        form_1 = UserUpdateForm(request.POST, instance=request.user)
        form_2 = ProfileUpdateForm(request.POST, request.FILES, instance =request.user.profile)

        if form_1.is_valid() and form_2.is_valid() :
            form_1.save()
            form_2.save()

            messages.success(request, "Updated!")
            return redirect('users:profile')

    else:
        form_1 = UserUpdateForm(instance=request.user)
        form_2 = ProfileUpdateForm(instance =request.user.profile)
    context ={
        'form_1' : form_1,
        'form_2' : form_2
    }
    return render(request, 'user/profile_update.html',context)

users/templates/user/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container special-container">
        <form method="POST">
        {% csrf_token %}
            <fieldset class="form-group form-style">
                <legend class = "border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group form-style">
                <button class="btn btn-dark bg-custom" type="submit">Log in</button>
            </div>
        </form>
        <div class ="border-top pt3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'users:register' %}">Sign Up</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/user/logout.html
{% extends 'base.html' %}
{% block content %}
<div class="container2 container special-container">
<h2>You have logged out</h2>
    <div class="content-section">
        <div class ="border-top pt3 text-muted">
            Login again<a href="{% url 'users:login' %}"> here</a>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/user/profile.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img profile-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ author.username }}</h2>
            <p class="text-secondary">{{ author.email }}</p>
            <a href="{% url 'users:profile_update'%}" style='color:gray;z-index:1;!important'>Update info</a>
        </div>
    </div>
    {% for post in posts %}
    <div class="row justify-content-center">
        <div class="container special-container m-3" style="background-color:rgba(40, 37, 118, 0.911); color:white;">
            <div class="row">
                <div class="col-1">
                    <img class="rounded-circle account-img-post" src="{{ post.author.profile.image.url }}">
                </div>
                <div class="col-11" style="padding-top: 0.5%;">
                    <h3 id="contentitle"><a href="{% url 'postcontents:contents' post.id %}" style="color:rgb(255, 175, 146)">{{ post.title }}</a></h1>
                        <h6 id="contentuser">{{ post.author }} posted</h6>
                        <h8 id="contentdate">{{ post.time }}</h8>
                </div>
            </div>
            <p id="thecontent">{{ post.content }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

users/templates/user/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">    
      <div class="container special-container">
          <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
              <fieldset class="form-group form-style">
                  <legend class = "border-bottom mb-4">Profile Info</legend>
                  {{ form_1|crispy }}
                  {{ form_2|crispy }}
              </fieldset>
              <div class="form-group form-style">
                  <button class="btn btn-dark bg-custom" type='submit'>Update</button>
              </div>
          </form>
      </div>
    </div>
{% endblock content %} 

users/templates/user/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container special-container">
        <form method="POST">
        {% csrf_token %}
            <fieldset class="form-group form-style">
                <legend class = "border-bottom mb-4">Sign Up</legend>
                {{ form|crispy }}
            </fieldset>
            <div id="alert-username" style="text-align:center;"></div>
            <div class="form-group form-style">
                <button class="btn btn-dark bg-custom" type="submit">Sign Up</button>
                <p class='pt-2'>Users created : {{ usercount }}</p>
            </div>
        </form>
        <div class ="border-top pt3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'users:login' %}">Log In</a>
            </small>
        </div>
    </div>

{% endblock content %}
{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#id_username").keyup(function(){
        var username = $("#id_username").val();
        console.log(username);
        if(username.length < 4){
            $("#alert-username").empty();
            $("#alert-username").append(
                "<p style='color:hotpink;'>Username too short</p>"
            )
        }
        else {
            $.ajax({
                url : "/search-username/",
                success : function(data){
                    var taken = false;
                    console.log(data);
                    $("#alert-username").empty();
                    for (i = 0 ; i < data.length ; i++){
                        if(username == data[i].fields.username){
                            console.log(data[i].username);
                            taken = true;  
                            break;
                        }    
                    }
                    if(taken == true){
                        $("#alert-username").append(
                            "<p style='color:hotpink;'>Username already taken</p>"
                        )
                        console.log("taken");
                    }
                    else {
                        $("#alert-username").append(
                            "<p style='color:yellow;'>Username not taken yet but please check again if it's following the criteria</p>"
                        )
                    }
                }
            })
        }
        
    })

    $("button").click((event)=> {
        event.preventDefault();
        var username = $("#id_username").val();
        console.log(username);
        var pass1 = $("#id_password1").val();
        var pass2 = $("#id_password2").val();
        if(pass1 != pass2){
            alert('password different')
        }
        else{
            $.ajax({
                url : "/register/",
                data : $("form").serialize(),
                type : "POST",
                error : function(response){
                    alert("Please read again password's criteria / Username not valid")
                    
                },
                success : function(response){
                    console.log(window.location.hostname)
                    $().messagelist
                    window.location.assign({% url 'users:login'%})
                }
            })
        }
    })
})

</script>
{% endblock script %}