feedback/urls.py
from django.urls import path

from . import views
app_name = 'feedback'

urlpatterns =[
    path('addFeedback/', views.addFeedback, name='addFeedback'),
] 

form/urls.py
from django.urls import path

from . import views
app_name = 'form'

urlpatterns =[
    path('add/', views.add, name='add'),
    path('index/', views.index, name='index'),
] 

main/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('kudos/', views.kudos_or_undo, name='kudos')
]

tk2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('postcontents/', include('postcontents.urls')),
    path('form/', include('form.urls', namespace='form')),
    path('', include('main.urls')),
    path('',include('users.urls')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from . import views as user_views
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('profile-update/', user_views.profile_update, name='profile_update'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('search-username/',user_views.getDataAllUser, name="search_username"),
    # path('register-check/',user_views.registerCheck, name="register_check"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% block meta %} {% endblock meta %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <title>{% block title %}NgapainAja{% endblock %}</title>
</head>
<!--Bootstrap Navbar-->


<header class="header fixed-top">
    <nav class="navbar navbar-expand-lg sticky-top navbar-light">
        <a class="navbar-brand" href="{% url 'main:home' %}" style="color: #FFF5EB;"><b>Ngapain Aja</b></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                <a class="nav-link" href="{% url 'form:add' %}" style="color: #FFF5EB;">Add Content</a> {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'users:profile' %}" style="color: #FFF5EB;">{{user.username}}</a>
                <a class="nav-link" href="{% url 'users:logout' %}" style="color: #FFF5EB;">Logout</a> {% else %}
                <a class="nav-link" href="{% url 'users:register' %}" style="color: #FFF5EB;">Sign Up</a>
                <a class="nav-link" href="{% url 'users:login' %}" style="color: #FFF5EB;">Login</a> {% endif %}
                <a class="nav-link" href="{% url 'feedback:addFeedback' %}" style="color: #FFF5EB;">Feedback</a>
            </div>
        </div>
    </nav>
</header>

<body>

    <div class="container">
        <div class='container3 pt-5' style='text-align: center'>
            {% if messages %} {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %} {% endif %}
        </div>
        {% block content %} {% endblock content %}
    </div>


    <div class="backgroundimg"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block script %} {% endblock script %}

</body>

<footer id="footer">
    <h3 style="font-size: 18px; padding-top: 10px;">+751 009 2323 || ngapainaja@gmail.com || ©2020 ngapainaja, All Rights Reserved</h3>

    {% comment %}
    <div class="row text-center mt-5">
        <div class="col-md-4">
            <h3 style="font-size: 18px; padding-top: 10px;">+751 009 2323</h3>
        </div>
        <div class="col-md-4">
            <h3 style="font-size: 18px; padding-top: 10px;">ngapainaja@gmail.com</h3>
        </div>
        <div class="col-md-4">
            <h3 style="font-size: 10px; padding-top: 15px;">©2020 ngapainaja, All Rights Reserved</h3>
        </div> {% endcomment %}
</footer>

</html>