form/urls.py
from django.urls import path

from . import views
app_name = 'form'

urlpatterns =[
    path('add/', views.add, name='add'),
    path('index/', views.index, name='index'),
] 

main/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('kudos/', views.kudos_or_undo, name='kudos')
]

postcontents/urls.py
from django.urls import path

from . import views
app_name = 'postcontents'

urlpatterns =[
    path('<int:id>/', views.postpage, name='postpage'),
    path('content/<int:id>/', views.contents, name='contents'),
    path('otherprofile/<str:parameter>/', views.otherprofile, name='otherprofile')
] 

tk2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('postcontents/', include('postcontents.urls')),
    path('form/', include('form.urls', namespace='form')),
    path('', include('main.urls')),
    path('',include('users.urls')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from form.models import PostModel

# Create your models here.
class Like(models.Model):
    user_kudos = models.ForeignKey(User, on_delete=models.CASCADE)
    post_kudos = models.ForeignKey(PostModel, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

main/views.py
from django.shortcuts import render, redirect
from .models import Like
from form.models import PostModel
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

def home(request):
    count_post = PostModel.objects.all().count()
    like_post = {}
    like_count = {}
    comment_count = {}
    pos_id = []
    if request.user.is_authenticated :
        for pos in PostModel.objects.all():
            pos_id.append(pos.id)
            like_count[pos.id] = pos.like_set.all().count()
            comment_count[pos.id] = pos.comment_set.all().count()
            if pos.like_set.filter(user_kudos=request.user) and True or False:
                like_post[pos.id] = 1
            else:
                like_post[pos.id] = 0

        postingan1 = {
            'count_post' : count_post,
            'postingan' : PostModel.objects.all(),
            'pos_id' : pos_id,
            'like_count' : like_count,
            'like_post' : like_post,
            'comment_count' : comment_count
        }
        return render(request, 'main/home.html', postingan1)
    messages.warning(request, 'Please login to continue')
    return redirect('/login/')

@login_required
def kudos_or_undo(request):
    if request.method == 'GET':
        post_id = request.GET['post_id']
        new_kudos, like_it = Like.objects.get_or_create(user_kudos=request.user, post_kudos=PostModel.objects.get(id=post_id))
        if not like_it:
            new_kudos.delete()
            return HttpResponse("You're Unlike this Post")
        return HttpResponse("You're Like this Post")
    else:
        return HttpResponse("Action Failed")

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
{% endblock page_title %}
{% endblock meta %}

{% block content %}
  <div class="container" style="margin-top: -45px; margin-bottom: -45px;">
    <div class="container detail-container" style="margin-bottom: 15px; text-align: center; padding-top: 5px; padding-bottom: 5px;">
      <a href="{% url 'form:add' %}">Post what you think...</a> <!--link to create post-->
    </div>
    <br>

    {% if count_post == 0 %}
      <div class="container detail-container" style="margin-bottom: 0; text-align: center; padding-bottom: 1px;">
        <p>Nothing here. Add the new post.</p>
      </div>
    {% else %}
      {% for post in postingan %}
        <div class="container" style="width: 100%; margin-bottom: 20px; margin-top: 0;">
          <div class="row justify-content-center">
              <div class="container detail-container" style="margin-bottom: 0">
                <div class="row">
                  <div class="col-1">
                      <a href="{% url 'postcontents:otherprofile' parameter=post.author.username %}">
                          <img class="rounded-circle account-img-post" src="{{ post.author.profile.image.url }}">
                      </a>
                  </div>
                  <div class="col-11" style="padding-top: 0.5%;">
                      <h3 id="contentitle">{{ post.title }}</h1>
                          <a href="{% url 'postcontents:otherprofile' parameter=post.author.username %}" style="color: black;">
                              <h6 id="contentuser">{{ post.author }} posted</h6>
                          </a>
                          <h8 id="contentdate">{{ post.time }}</h8>
                  </div>
                </div>
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col-11">
                        <p id="thecontent" style="padding-bottom: 0;">{{ post.content }}</p>
                    </div>
                </div>
                <hr>
                <div class="d-flex justify-content-end">
                  <a class="p-2"  style="margin-top: -8px;" href="{% url 'postcontents:contents' post.id %}">Comment</a>
                  <p id="ccount{{post.id}}" style="margin-right: 5px;"></p>
                  <p>|</p>
                  <a class="likebutton p-2"  style="margin-top: -8px;" id="like{{post.id}}" href="#" data-catid="{{ post.id }}" title=""></a>
                  <p id="count{{post.id}}"></p>
                </div>
              </div>
          </div>
          <p class="action" id="action{{post.id}}" style="text-align: center;"></p>
        </div>
        <br>
      {% endfor %}
    {% endif %}
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script>
    var l_post = {{like_post|escapejs}};
    var l_count = {{like_count|escapejs}};
    var p_id = {{pos_id|escapejs}};
    var c_count = {{comment_count|escapejs}};

    p_id.forEach(id_pos => {
      if (l_post[id_pos]) $("#like" + id_pos).attr("title", "You're Like This Post");
      document.getElementById("like" + id_pos).innerHTML = l_post[id_pos] ? "Liked!" : "Like It!";
      document.getElementById("count" + id_pos).innerHTML = l_count[id_pos];
      document.getElementById("ccount" + id_pos).innerHTML = c_count[id_pos];
    });

    $(document).ready(function() {
      $('.action').slideUp(0);
    });

    $('.likebutton').click(function(){
      var catid = $(this).attr("data-catid");
      var like_ = document.getElementById("like" + catid).textContent;
      var count_like = parseInt(document.getElementById("count" + catid).textContent);
      var x_coord = $(document).scrollTop();
      $.ajax({
        type: "GET",
        url: "{% url 'main:kudos' %}",
        data: {post_id: catid},
        success: function(data) {
          if (like_ == "Liked!") $("#like" + catid).attr("title", "");
          else $("#like" + catid).attr("title", "You're Like This Post");
          
          $('#action' + catid).slideDown(300);
          document.getElementById("action" + catid).innerHTML = data;
          document.getElementById("like" + catid).innerHTML = (like_ == "Liked!") ? "Like It!" : "Liked!";
          document.getElementById("count" + catid).innerHTML = (like_ == "Liked!") ? count_like - 1 : count_like + 1;
          $('#action' + catid).delay(5000).slideUp(300);
          window.scrollTo(0, x_coord);
        }
      });
    });
  </script>
{% endblock content %}